<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="BGM" failures="1" tests="8" name="com.appium.scripts.ListenersTest" time="1.639" errors="0" timestamp="2022-01-25T22:18:52 IST" skipped="7">
  <testcase classname="com.appium.scripts.ListenersTest" name="test1" time="1.639">
    <failure message="expected [page title] but found [ChromeDriver - WebDriver for Chrome - Downloads]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [page title] but found [ChromeDriver - WebDriver for Chrome - Downloads]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.appium.scripts.ListenersTest.test1(ListenersTest.java:15)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test1 -->
  <system-out/>
  <testcase classname="com.appium.scripts.ListenersTest" name="test5">
    <skipped/>
  </testcase> <!-- test5 -->
  <system-out/>
  <testcase classname="com.appium.scripts.ListenersTest" name="test2">
    <skipped/>
  </testcase> <!-- test2 -->
  <system-out/>
  <testcase classname="com.appium.scripts.ListenersTest" name="test3">
    <skipped/>
  </testcase> <!-- test3 -->
  <system-out/>
  <testcase classname="com.appium.scripts.ListenersTest" name="test8">
    <skipped/>
  </testcase> <!-- test8 -->
  <system-out/>
  <testcase classname="com.appium.scripts.ListenersTest" name="test6">
    <skipped/>
  </testcase> <!-- test6 -->
  <system-out/>
  <testcase classname="com.appium.scripts.ListenersTest" name="test7">
    <skipped/>
  </testcase> <!-- test7 -->
  <system-out/>
  <testcase classname="com.appium.scripts.ListenersTest" name="test4">
    <skipped/>
  </testcase> <!-- test4 -->
  <system-out/>
</testsuite> <!-- com.appium.scripts.ListenersTest -->
